### ISSUE TITLE
Access?

### ISSUE THREAD

**Issue by Lilykhan786** [Dev-Lily-Discord/Dev-Lily#1]
Hey, I don't have perms to edit this repo, 👀 also add the server link in the readme ~~(shameless ad smh)~~
also ppl who will contribute to this repo (server members only) will get free hacker plan hehe

**Comment by Lilykhan786** [comment]
@CoolCoderSJ hello?

**Comment by ShuchirJ** [comment]
@LilyKhan786 
- I’ll add the link later when I’m free
- haha sorry, the base was set to read-only. All org members should be able to edit now.
