### ISSUE TITLE
discord.py is dead

### ISSUE THREAD

**Issue by leon332157** [Dev-Lily-Discord/Dev-Lily#2]
Since discord.py is dead, I suggest using another fork or use another library.

**Comment by Lilykhan786** [comment]
wait but we r not making a bot oh wait r we? 🤔

**Comment by ShuchirJ** [comment]
@Lilykhan786 the polls suggest we should, your call though.
@leon332157 any suggestions?

**Comment by leon332157** [comment]
https://github.com/hikari-py/hikari

**Comment by Lilykhan786** [comment]
hmm well idk the whole idea 🤔 so what's the plan so far? can u explain?

**Comment by ShuchirJ** [comment]
Thanks leon

@Lilykhan786 so far we have-

- A site for the discord server, featuring various elements from different users. So far we have 
    - A discord bot that primarily reads users' connections, gets their GitHub username and shows their Github profile. (Spot)
    - (BarioIDL) might feature their games.

**Comment by Lilykhan786** [comment]
Bario's game oh god, (ik him he can do it, I hope so)
well we lack in features 🤔 _( btw I won't be active on discord for one week or so)_ could u keep me updated about the ideas 
and keep asking for more ides? 

1. Should we ask repl talk ppl to join us? 👀 (we will see about that later)
2. Create a diff/private channel and give special role to the ppl who are working on this project, so when they work they can discuss stuff about that on that diff channel.
3. Get more details about the game form Bario.

**Comment by ShuchirJ** [comment]
@Lilykhan786 
1. I mean we could but I thought this was intended as a server event :thonk:
2. Can I have perms to do that pls
3. yep will do

**Comment by ShuchirJ** [comment]
Btw #3 can be used for general talk now :)
